// react/20-typescript/04-listsandforms/src/components/ShoppingList.tsx
import React from 'react';
import ShoppingItem from '../models/ShoppingItem';
import Row from './Row';

interface Props {
	list:ShoppingItem[];
	removeFromList(id:number):void;
}

export default class ShoppingList extends React.Component<Props> {
	
	render() {
		let items = this.props.list.map((item) => {
			return (
				<Row key={item.id} item={item} removeFromList={this.props.removeFromList}/>
				)
		})
		return (
			<table>
				<thead>
					<tr>
						<th>Type</th>
						<th>Count</th>
						<th>Price</th>
						<th>Remove</th>
					</tr>
				</thead>
				<tbody>
				{items}
				</tbody>
			</table>
		)
	}
}

// angular/m-shoppingapp/src/app/components/shoppinglist.component.ts
import {Component,OnInit} from '@angular/core';
import {ShoppingItem} from '../models/shoppingitem.model';
import {ShoppingService} from '../services/shoppingservice.service';
import {LoginService} from '../services/loginservice.service';
import {Router} from '@angular/router'

@Component({
	selector:"shoppinglist",
	templateUrl:"./shoppinglist.component.html"
})
export class ShoppingList implements OnInit {
	
	shoppinglist:ShoppingItem[] = []
	
	constructor(private _shopping:ShoppingService, private _login:LoginService,private _router:Router) {}
	
	ngOnInit() {
		if(!this._login.isUserLogged()) {
			this._router.navigate(['/']);
		} else {
			this.getList()
		}
	}
	
	getList() {
		this._shopping.getList().subscribe(
			data => this.shoppinglist = data,
			error => console.log(error),
			() => console.log("Get list done")
		)
	}
	
	removeFromList(id:number) {
		this._shopping.removeFromList(id).subscribe(
			data => this.getList(),
			error => console.log(error),
			() => console.log("Remove from list done")
		)
	}
}
<table class="table table-striped">
	<thead>
		<tr>
			<th>Type</th>
			<th>Count</th>
			<th>Price</th>
			<th>Remove</th>
		</tr>	
	</thead>
	<tbody>
		<tr *ngFor="let item of shoppinglist">
			<td>{{item.type}}</td>
			<td>{{item.count}}</td>
			<td>{{item.price}}</td>
			<td><button class="btn btn-danger" (click)="removeFromList(item.id)">Remove</button></td>
		</tr>
	</tbody>
</table>
