// react/11-context_and_hoc/src/components/ContactList.js
import React from 'react';
import StateManager from '../statemanager/StateManager';

class ContactList extends React.Component {
	render() {
		let contacts = this.props.list.map(contact => {
			return (
				<tr key={contact.id}>
					<td>{contact.firstname}</td>
					<td>{contact.lastname}</td>
					<td>{contact.phone}</td>
					<td>{contact.email}</td>
					<td>{contact.address}</td>
					<td>{contact.city}</td>
					<td><button onClick={() => this.props.removeFromList(contact.id)}>Remove</button></td>
				</tr>
			)
		})
		return(
			<table>
				<thead>
					<tr>
						<th>First name</th>
						<th>Last name</th>
						<th>Phone</th>
						<th>Email</th>
						<th>Address</th>
						<th>City</th>
						<th>Remove</th>
					</tr>
				</thead>
				<tbody>
				{contacts}
				</tbody>
			</table>
		)
	}
	
	
}

export default StateManager(ContactList);

// angular/j-routing-one/src/app/components/contactlist.component.ts
import {Component, OnInit} from '@angular/core';
import {Contact} from '../models/contact.model';
import {ContactService} from '../services/contactservice.service';

@Component({
	selector:"contact-list",
	templateUrl:"./contactlist.component.html"
})
export class ContactList implements OnInit {
	

	contactList:Contact[] = [];
	
	constructor(private _contactService:ContactService) {}
	
	ngOnInit() {
		this.getList();
	}
	
	getList() {
		this.contactList = this._contactService.getList();
	}
	
	
	removeFromList(id:number) {
		this._contactService.removeFromList(id);
		this.getList();
	}
}
<table>
	<thead>
		<tr>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Email</th>
			<th>Phone</th>
			<th>Remove</th>
		</tr>	
	</thead>
	<tbody>
		<tr *ngFor="let c of contactList">
			<td>{{c.firstname}}</td>
			<td>{{c.lastname}}</td>
			<td>{{c.email}}</td>
			<td>{{c.phone}}</td>
			<td><button (click)="removeFromList(c.id)">Remove</button></td>
		</tr>
	</tbody>
</table>
