// react/08-redux_test/src/components/ContactForm.js
import React from 'react';
import {connect} from 'react-redux';

class ContactForm extends React.Component {

	constructor(props) {
		super(props);
		this.state = {
			firstname:"",
			lastname:""
		}
	}
	
	onChange=(event) => {
		this.setState({
			[event.target.name]:event.target.value	
		})
	}

	onSubmit = (event) => {
		event.preventDefault();
		let contact = {
			...this.state
		}
		console.log("ContactForm, onSubmit: dispatch ADD_TO_LIST");
		this.props.dispatch({
			type:"ADD_TO_LIST",
			contact:contact
		})
	}

	render() {
		return(
			<form onSubmit={this.onSubmit}>
				<label htmlFor="firstname">First name:</label>
				<input type="text"
					name="firstname"
					onChange={this.onChange}
					value={this.state.firstname}/>
				<br/>
				<label htmlFor="lastname">Last Name:</label>
				<input type="text"
					name="lastname"
					onChange={this.onChange}
					value={this.state.lastname}/>
				<br/>
				<input type="submit" value="Add"/>
			</form>
		)
	}
}

export default connect()(ContactForm);

// angular/j-routing-one/src/app/components/contactform.component.ts
import {Component} from '@angular/core';
import {Contact} from '../models/contact.model';
import {ContactService} from '../services/contactservice.service';

@Component({
	selector:"contact-form",
	templateUrl:"./contactform.component.html"
})
export class ContactForm {
	contact:Contact = new Contact("","","","",0);
	
	constructor(private _contactService:ContactService) {}
	
	addToList() {
		this._contactService.addToList(this.contact);
		this.contact = new Contact("","","","",0)
	}
}
<form (ngSubmit)="addToList()" #contactForm="ngForm">
	<label for="firstname">First Name</label>
	<input type="text"
			id="firstname"
			name="firstname"
			[(ngModel)]="contact.firstname"/>
	<br/>
	<label for="lastname">Last Name</label>
	<input type="text"
			id="lastname"
			name="lastname"
			[(ngModel)]="contact.lastname"/>
	<br/>
	<label for="email">Email</label>
	<input type="email"
			id="email"
			name="email"
			[(ngModel)]="contact.email"/>
	<br/>
	<label for="phone">Phone</label>
	<input type="text"
			id="phone"
			name="phone"
			[(ngModel)]="contact.phone"/>
	<br/>
	<input type="submit" value="Add Contact"/>
</form>
