// react/05-lists/src/components/ContactList.js
import React from 'react';
import {Table,Button} from 'semantic-ui-react';

export default class ContactList extends React.Component {
	
	render() {
		let contacts = this.props.list.map((contact) => {
			return (
				<Table.Row key={contact.id}>
					<Table.Cell>{contact.firstname}</Table.Cell>
					<Table.Cell>{contact.lastname}</Table.Cell>
					<Table.Cell>{contact.email}</Table.Cell>
					<Table.Cell>{contact.phone}</Table.Cell>
					<Table.Cell>
						<Button onClick={() => this.props.removeFromList(contact.id)}>Remove</Button>
					</Table.Cell>
				</Table.Row>
			)	
		});
		return(
			<Table striped>
				<Table.Header>
					<Table.Row>
						<Table.HeaderCell>First Name</Table.HeaderCell>
						<Table.HeaderCell>Last Name</Table.HeaderCell>
						<Table.HeaderCell>Email</Table.HeaderCell>
						<Table.HeaderCell>Phone</Table.HeaderCell>
						<Table.HeaderCell>Remove</Table.HeaderCell>
					</Table.Row>
				</Table.Header>
				<Table.Body>
				{contacts}
				</Table.Body>
			</Table>
		)
	}
}

// angular/j-routing-one/src/app/components/contactlist.component.ts
import {Component, OnInit} from '@angular/core';
import {Contact} from '../models/contact.model';
import {ContactService} from '../services/contactservice.service';

@Component({
	selector:"contact-list",
	templateUrl:"./contactlist.component.html"
})
export class ContactList implements OnInit {
	

	contactList:Contact[] = [];
	
	constructor(private _contactService:ContactService) {}
	
	ngOnInit() {
		this.getList();
	}
	
	getList() {
		this.contactList = this._contactService.getList();
	}
	
	
	removeFromList(id:number) {
		this._contactService.removeFromList(id);
		this.getList();
	}
}
<table>
	<thead>
		<tr>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Email</th>
			<th>Phone</th>
			<th>Remove</th>
		</tr>	
	</thead>
	<tbody>
		<tr *ngFor="let c of contactList">
			<td>{{c.firstname}}</td>
			<td>{{c.lastname}}</td>
			<td>{{c.email}}</td>
			<td>{{c.phone}}</td>
			<td><button (click)="removeFromList(c.id)">Remove</button></td>
		</tr>
	</tbody>
</table>
